import { MemoryGameLevel } from "../utils/memoryGameLevel";

export const GameLevels = [
  new MemoryGameLevel("Easy", 4, ["card-0", "card-1"]),
  new MemoryGameLevel("Easy", 4, ["card-0", "card-1"]),
  new MemoryGameLevel("Easy", 4, ["card-0", "card-1"]),
  new MemoryGameLevel("Easy", 4, ["card-0", "card-1"]),
  new MemoryGameLevel("Easy", 4, ["card-0", "card-1"]),
  new MemoryGameLevel("Medium", 6, ["card-0", "card-1", "card-2"]),
  new MemoryGameLevel("Medium", 6, ["card-0", "card-1", "card-2"]),
  new MemoryGameLevel("Medium", 6, ["card-0", "card-1", "card-2"]),
  new MemoryGameLevel("Medium", 6, ["card-0", "card-1", "card-2"]),
  new MemoryGameLevel("Medium", 6, ["card-0", "card-1", "card-2"]),
  new MemoryGameLevel("Medium", 8, ["card-0", "card-1", "card-2", "card-3"]),
  new MemoryGameLevel("Medium", 8, ["card-0", "card-1", "card-2", "card-3"]),
  new MemoryGameLevel("Medium", 8, ["card-0", "card-1", "card-2", "card-3"]),
  new MemoryGameLevel("Medium", 8, ["card-0", "card-1", "card-2", "card-3"]),
  new MemoryGameLevel("Medium", 8, ["card-0", "card-1", "card-2", "card-3"]),
  new MemoryGameLevel("Hard", 10, [
    "card-0",
    "card-1",
    "card-2",
    "card-3",
    "card-4",
  ]),
  new MemoryGameLevel("Hard", 10, [
    "card-0",
    "card-1",
    "card-2",
    "card-3",
    "card-4",
  ]),
  new MemoryGameLevel("Hard", 10, [
    "card-0",
    "card-1",
    "card-2",
    "card-3",
    "card-4",
  ]),
  new MemoryGameLevel("Hard", 10, [
    "card-0",
    "card-1",
    "card-2",
    "card-3",
    "card-4",
  ]),
  new MemoryGameLevel("Hard", 10, [
    "card-0",
    "card-1",
    "card-2",
    "card-3",
    "card-4",
  ]),
];
